name: haskell-slackin
version: '0.1.0.0'
author: yamadapc
maintainer: tacla.yamada@gmail.com
license: MIT
extra-source-files:
- ChangeLog.md

dependencies:
- base >=4.8 && <4.10
- yesod
- monad-logger
- wreq
- lens
- text
- stm
- lens-aeson
- vector
- yesod-websockets
- aeson

executables:
  haskell-slackin:
    main: Main.hs
    source-dirs:
    - src
    ghc-options: -O2 -threaded
